openapi: 3.0.3
info:
  title: My Service API
  version: 1.0.0
  description: |
    API do serviço **my-other-service**, configurado no gateway do Kong.
servers:
  - url: https://api.exemplo.com/my-other-service
paths:
  /:
    get:
      summary: Exemplo de endpoint do serviço
      responses:
        '200':
          description: Sucesso