name: Sync Guides to ReadMe

on:
  push:
    branches:
      - main

jobs:
  upload-guides:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Guides to ReadMe
        uses: readmeio/rdme@v10.5.3
        with:
          rdme: |
            for guide in docs/guides/*.md; do
              echo "📘 Uploading $guide..."
              rdme docs upload "$guide" --key=${{ secrets.README_API_KEY }} --branch=main
            done
