name: Sync API Specs to ReadMe

on:
  push:
    branches:
      - main

jobs:
  upload-api-specs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload OpenAPI specs to ReadMe
        uses: readmeio/rdme@v10.5.3
        with:
          rdme: |
            for doc in docs/specs/*/index.yaml; do
              service_name=$(basename "$(dirname "$doc")")
              echo "📤 Uploading $service_name API spec..."
              rdme openapi upload "$doc" --key=${{ secrets.README_API_KEY }} --branch=main --slug="$service_name"
            done